version: "3.7"

services:
  api:
    build:
      context: api-laravel
      dockerfile: Dockerfile
      args:
        user: w2l
        uid: 1000
    image: api_laravel
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./api-laravel:/var/www
    networks:
      - application

  client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        user: w2l
        uid: 1000
    volumes:
      - ./client:/app
    networks:
      - application
    ports:
      - 3000:3000
      

  nginx: 
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./api-laravel:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - application
  
  mysql: 
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - application

networks:
  application:
    driver: bridge